In [1]:
!pip install kaggle

In [2]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [3]:
!kaggle datasets download arshid/iris-flower-dataset

Dataset URL: https://www.kaggle.com/datasets/arshid/iris-flower-dataset
License(s): CC0-1.0
  0% 0.00/0.99k [00:00<?, ?B/s]
100% 0.99k/0.99k [00:00<00:00, 2.07MB/s]


In [4]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.model_selection import train_test_split

In [5]:
from zipfile import ZipFile

flower='/content/iris-flower-dataset.zip'
with ZipFile(flower, 'r') as zip:
  zip.extractall()
  print('The dataset is extracted')


The dataset is extracted


In [6]:
iris_data=pd.read_csv('/content/IRIS.csv')
iris_data

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
iris_data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [8]:
iris_data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [9]:
iris_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [10]:
iris_data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [12]:
iris_data['species'].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [13]:
iris_data.shape

(150, 5)

In [14]:
iris_data.replace({'species':{'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}},inplace=True)

<ipython-input-14-9a0c87f41cf3>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  iris_data.replace({'species':{'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}},inplace=True)


In [16]:
X=iris_data.drop(columns='species',axis=1)
Y=iris_data['species']

In [17]:
print(X)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [18]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64


In [19]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [20]:
print(X.shape,X_train.shape,X_test.shape)

(150, 4) (120, 4) (30, 4)


In [21]:
from sklearn.preprocessing import StandardScaler


In [22]:
scaler = StandardScaler()

In [23]:
X_train_std = scaler.fit_transform(X_train)


In [24]:
X_test_std = scaler.transform(X_test)

In [25]:
import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras

In [29]:
model = keras.Sequential([
                          keras.layers.Flatten(input_shape=(4,)),
                          keras.layers.Dense(20,activation='relu'),
                          keras.layers.Dense(3,activation='softmax')
])

In [30]:
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])


In [31]:
history = model.fit(X_train_std,Y_train,validation_split=0.1,epochs=10)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - accuracy: 0.5297 - loss: 1.0761 - val_accuracy: 0.6667 - val_loss: 0.8981
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5334 - loss: 1.0403 - val_accuracy: 0.6667 - val_loss: 0.8612
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5424 - loss: 1.0065 - val_accuracy: 0.6667 - val_loss: 0.8269
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5519 - loss: 0.9743 - val_accuracy: 0.7500 - val_loss: 0.7949
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5519 - loss: 0.9436 - val_accuracy: 0.7500 - val_loss: 0.7652
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5519 - loss: 0.9143 - val_accuracy: 0.7500 - val_loss: 0.7376
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5670 - loss: 0.8864 - val_accuracy: 0.7500 - val_loss: 0.7124
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5911 - loss: 0.8598 - val_accuracy: 0.7500 - val_loss: 0.6891
Epoch

In [32]:
loss,accuracy=model.evaluate(X_test_std,Y_test)
print(accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.7002
0.6666666865348816


In [33]:
y_pred = model.predict(X_test_std)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


In [34]:
print(y_pred)

[[0.8120863  0.13307883 0.05483488]
 [0.7519049  0.18073414 0.067361  ]
 [0.23134466 0.5788778  0.1897775 ]
 [0.7183551  0.19846296 0.08318181]
 [0.7659125  0.1594125  0.07467503]
 [0.33285198 0.24006964 0.4270784 ]
 [0.6764207  0.21763366 0.1059457 ]
 [0.29040992 0.39765173 0.31193826]
 [0.3023116  0.39636222 0.30132625]
 [0.7094477  0.20708813 0.08346414]
 [0.7740351  0.12993227 0.0960326 ]
 [0.7988134  0.15131524 0.04987133]
 [0.74722135 0.16171275 0.09106597]
 [0.77375215 0.1265196  0.0997282 ]
 [0.34473926 0.29989165 0.35536903]
 [0.30285865 0.33424583 0.36289552]
 [0.53293973 0.38631204 0.08074822]
 [0.27910104 0.42141488 0.29948413]
 [0.35781142 0.29852572 0.34366286]
 [0.25038213 0.53179485 0.21782301]
 [0.32222345 0.29394895 0.38382763]
 [0.30073988 0.31571224 0.38354784]
 [0.33693638 0.33625153 0.32681203]
 [0.261111   0.48199445 0.25689453]
 [0.26432225 0.4519547  0.28372297]
 [0.7582101  0.16962191 0.07216792]
 [0.77558845 0.15768705 0.06672455]
 [0.3066477  0.37366202 0.31

In [35]:
my_list =[0.2362377,0.25563216,0.5081301]
index_of_max_value = np.argmax(my_list)
print(my_list)
print(index_of_max_value)

[0.2362377, 0.25563216, 0.5081301]
2


In [36]:
y_pred_labels = [np.argmax(i) for i in y_pred]

In [40]:
from google.colab import files
X_test.to_csv('flower_test',index=False)
files.download('flower_test')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [41]:
input_data=(4.6,3.4,1.4,0.3)

input_data_as_numpy_array=np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

input_data_std =scaler.transform(input_data_reshaped)

prediction = model.predict(input_data_std)
print(prediction)

prediction_label=[np.argmax(prediction)]
print(prediction_label)

if(prediction_label[0]==0):
  print('Species is Iris-setosa')
elif(prediction_label[0]==1):
  print('Species is Iris-versicolor')
else:
  print('Species is Iris-virginica')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[[0.81208634 0.13307883 0.05483488]]
[0]
Species is Iris-setosa


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
